### ISSUE TITLE
[Suggestion] The placeholders should not disable the scrolling functionality? 

### ISSUE THREAD

**Issue by sasojadrovski** [HamzaGhazouani/HGPlaceholders#10]
Hi @HamzaGhazouani,

I was thinking whether it would be nice to have the option to choose whether the placeholders should disable the scrolling functionalities of `UITableView`s and `UICollectionView`s. 

One good example why I think that sometimes we need to have that one enabled is let's say you want to check for new data by triggering a pull to refresh action. Currently, if an empty state is visible, there is no way you can trigger this action, since the scrolling is disabled.

What are your thoughts on this?

Best regards,
Sasho

**Comment by sasojadrovski** [comment]
@HamzaGhazouani, any thoughts on this?

**Comment by HamzaGhazouani** [comment]
Hi @sasojadrovski, 

Sorry for my late reply.
If the TableView has the UIRefreshScroll the scroll is enabled, I should check if it's the case in the CollectionView.
If the user would like to refresh we could use the placeholder action button.
But I think it can be interesting to keep always the scroll enabled and if the user would like to disable it, he can use directly `alwaysBounceVertical = false`
The disadvantage is that we should do it every time before/after showing any placeholder...
May be we can add a new property to ask the user if he would like to have scroll or not when the placeholder is shown...

**Comment by sasojadrovski** [comment]
Hey @HamzaGhazouani, no worries for the delayed reply, we are all busy with work :) I am super glad that you replied anyway, so kudos to that!

I think that the best option is the last one you've mentioned, adding a new property that can be set by the developer if he would like to allow scrolling when the placeholder is visible. This can be found in dzenbot's [DZNEmptyDataSet](https://github.com/dzenbot/DZNEmptyDataSet) library where he implemented it as a delegate method (because the entire library was built around delegates), so in your case, a property would be great. 

Let me know your thoughts and whether you will be adding this feature soon.

Thanks!

**Comment by HamzaGhazouani** [comment]
@sasojadrovski Perfect, let's implement that in the next release 🎉

**Comment by junweimah** [comment]
Hi

Is the scrolling enabled release out?

**Comment by HamzaGhazouani** [comment]
Hi @junweimah, 
Not yet this feature will be available in the next release (in two weeks)

**Comment by junweimah** [comment]
@HamzaGhazouani 
Ok thanks.

**Comment by HamzaGhazouani** [comment]
Available in [HGPlaceholders 0.3.0](https://github.com/HamzaGhazouani/HGPlaceholders/releases/tag/0.3.0)
