### ISSUE TITLE
Could not cast value of type 'UITableView' to 'HGPlaceholders.TableView'

### ISSUE THREAD

**Issue by magicmikek** [HamzaGhazouani/HGPlaceholders#14]
The cast for me does not work: The error appears here:

`placeholderTableView = notificationTableView as! TableView`

I am not using a UITableViewController, but just a UITableview in a UIViewController. 

I follow the demo project and create the placeholderTableView as my UITableView (notificationTableView) as TableView. 
Force Cast creates the following issue:
**Could not cast value of type 'UITableView' to 'HGPlaceholders.TableView'**

Optional cast with ? does not do anything.

**Comment by HamzaGhazouani** [comment]
Hi magicmikek, in your case you don't need any cast

**IB**
In the third tab, put Class: TableView  and Module: HGPlaceholder 
`@IBOutlet weak var notificationTableView: TableView!`

**Code** 
`var notificationTableView = TableView(...)`

**Comment by magicmikek** [comment]
Unfortunately I can only initialise the TableView like this: 
<img width="536" alt="screen shot 2017-09-18 at 17 32 48" src="https://user-images.githubusercontent.com/7288679/30550361-825ffe0c-9c97-11e7-8611-0bb5eca5b618.png">

I can't init with a Frame.

**Comment by magicmikek** [comment]
I solved it by editing the class TableView in Podfile. 
For the override init with frame, I wrote:
`override **public** init`

**Comment by HamzaGhazouani** [comment]
@magicmikek yes, I forgot to put `public` keyword in the method `init(frame...)`  I will publish a new version with this change soon, thanks for your contribution.
