### ISSUE TITLE
Archive Fails

### ISSUE THREAD

**Issue by bubudrc** [HamzaGhazouani/HGPlaceholders#15]
Hi,

I was trying to archive a project using this library, but... fails...

Attached an image error..

<img width="844" alt="screen shot 2017-09-18 at 12 02 30 pm" src="https://user-images.githubusercontent.com/619159/30548741-577c7cde-9c69-11e7-8ddc-74b991469757.png">

how can I fix this?

**Comment by HamzaGhazouani** [comment]
Hi @bubudrc, Which version of Xcode you use ? it's related to this #7 ?

**Comment by bubudrc** [comment]
I'm using:  **Xcode Version 8.3.2 (8E2002)**

I think, this issue it's not related with the one that are you mentioned

**Comment by HamzaGhazouani** [comment]
Hi @bubudrc, I can't reproduce it, can you please upload a project with this issue ?

**Comment by HamzaGhazouani** [comment]
Hi @bubudrc, the issue is fixed in the version 0.2.6
