### ISSUE TITLE
Action button is not visible, but tapping on the white space is printing logs.

### ISSUE THREAD

**Issue by junweimah** [HamzaGhazouani/HGPlaceholders#19]
Hi,

I played around the example project and found that the placeholder has a button "try again", and user can tap that.

However in my project, there is no action button, but I can tap on the white space below the subtitle and the log is printing "Placeholder action button tapped"

How and where do I set the action button to visible?

Thanks

**Comment by HamzaGhazouani** [comment]
Hi @junweimah,  the background color of the action button, by default, is the tintColor of the TableView, just change it. Or if you  would like to customize it you can use `PlaceholderStyle`

**Comment by junweimah** [comment]
How do I use PlaceholderStyle?

In other question, you guided me to this code : 

```
//test a custom placeholder
            let provider: PlaceholdersProvider = .default
            var noConnectionData: PlaceholderData = .noConnection
            noConnectionData.title = "My custom title"
            noConnectionData.subtitle = "Please check your connection !!! "
            
            let noConnectionPlaceholder = Placeholder(data: noConnectionData, style: PlaceholderStyle(), key: .noConnectionKey)
            provider.add(placeholders: noConnectionPlaceholder)
            self.tvBug.placeholdersProvider = provider
```

Now in let `noConnectionPlaceholder = Placeholder(data: noConnectionData, style: PlaceholderStyle(), key: .noConnectionKey)`, for `PlaceholderStyle()` I have to cuztomize right?

What do I need to do to change the text and background color of the action button?

**Comment by HamzaGhazouani** [comment]
So to customize the style you can do like that :
``` 
//test a custom placeholder
let provider: PlaceholdersProvider = .default
var noConnectionStyle = PlaceholderStyle()
noConnectionStyle.actionBackgroundColor = .red
...
var noConnectionData: PlaceholderData = .noConnection
noConnectionData.title = "My custom title"
noConnectionData.subtitle = "Please check your connection !!! "
    
let noConnectionPlaceholder = Placeholder(data: noConnectionData, noConnectionStyle: , key: .noConnectionKey)
provider.add(placeholders: noConnectionPlaceholder)
self.tvBug.placeholdersProvider = provider
```

**Comment by junweimah** [comment]
Wow. it works! Thanks

For the action button tap function

f```
unc view(_ view: Any, actionButtonTappedFor placeholder: Placeholder) {
        //do something here
        print("this is placeholder tapped !!! ")
    }
```

Why is this not printed out?

**Comment by HamzaGhazouani** [comment]
You are welcome :) 
It's not printed out because your controller is not conform to the protocol PlaceholderDelegate: 

```
extension ViewController: PlaceholderDelegate {
    
    func view(_ view: Any, actionButtonTappedFor placeholder: Placeholder) {
        print(placeholder.key.value)
        placeholderTableView?.showDefault()
    }
}
```

**Comment by junweimah** [comment]
My vc actually have this right now

`class BugTabTableViewController: UITableViewController, IndicatorInfoProvider, PlaceholderDelegate{`

  ```
  func view(_ view: Any, actionButtonTappedFor placeholder: Placeholder) {
        //do something here
        print("this is in big tv vc placeholder tapped !!! ")
        print("this is key value \(placeholder.key.value)")
//        self.tvBug.showDefault()
    }
```

However this is not printed out

**Comment by HamzaGhazouani** [comment]
Hi @junweimah, 

I think you missed to set the placeholderDelegate to self: 
`tvBug.placeholderDelegate = self`

**Comment by junweimah** [comment]
WOW. 

Thanks. It works!

Thank you so much. Best git library owner ever. Answered all my questions. Fast reply. Good job

**Comment by HamzaGhazouani** [comment]
My pleasure, thank you for your contribution and for your kind words :)
