### ISSUE TITLE
Unable to add custom placeholder

### ISSUE THREAD

**Issue by theblixguy** [HamzaGhazouani/HGPlaceholders#25]
So I define a custom placeholder and add it to the table:

```
func addTimeableNotFoundPlaceholder() {
        let provider: PlaceholdersProvider = .default
        var noTimetableFound: PlaceholderData = .error
        noTimetableFound.title = "No timetable found"
        noTimetableFound.subtitle = "The app was unable to find your calendar..."
        let noTimetableFoundPlaceholder = Placeholder(data: noTimetableFound, style: PlaceholderStyle(), key: .custom(key: "noTimetableFound"))
        provider.add(placeholders: noTimetableFoundPlaceholder)
        timetableTable.placeholdersProvider = provider
    }
```

and then when my app is unable to find the user's calendar, it calls 

`self.timetableTable.showCustomPlaceholder(with: PlaceholderKey.custom(key: "noTimetableFound"))`

but the tableview does not show the custom placeholder, it just shows the "No results found" placeholder.

**Comment by Faari7** [comment]
can you tell me how you add custom placeholder? i find it difficult to implement

**Comment by theblixguy** [comment]
For my app, I created a [utility class](https://gist.github.com/theblixguy/d836ba66569c34c7061a81bf903c5e0d) to generate the placeholders I need.

After that, I set up the placeholder view and add my placeholders to the placeholders provider:

```
self.myTableView.placeholderDelegate = self
self.myTableView.placeholdersProvider = .default
self.myTableView.placeholdersProvider.add(placeholders: PlaceholderGenerator.createTimeableNotFoundPlaceholder())
self.myTableView.placeholdersProvider.add(placeholders: PlaceholderGenerator.createPermissionNotGrantedPlaceholder())
```

Finally, I show the custom placeholder by calling ` self.timetableTable.showCustomPlaceholder(with: PlaceholderKey.custom(key: "permNotGranted"))` where `key` is the unique key associated with the placeholder I want to show.

**Comment by Faari7** [comment]
did you add that utility class to every table view class in a storyboard, where ever you need to display custom placeholder?

**Comment by theblixguy** [comment]
It’s a utility class with static methods, so you just simply call the methods whenever you need to insert a custom placeholder into the table view’s placeholder provider.

**Comment by Faari7** [comment]
1- I created a utility class and assign it to the table view where I needed to use table view placeholder.
2- created a variable in VC  "var placeholderTableView: TableView?"
3- In setup GUI
        self.placeholderTableView?.placeholdersProvider = .default
        self.placeholderTableView?.placeholdersProvider.add(placeholders: TableViewPlaceholder.createPlaceholder1())
4-  it show default placeholder not custom placeholder which i setting

**Comment by theblixguy** [comment]
> I created a utility class and assign it to the table view where I needed to use table view placeholder.

How can you "assign" a utility class to a table view?

> created a variable in VC "var placeholderTableView: TableView?"

You need an IBOutlet that connects to the table view in your Storyboard.

**Comment by HamzaGhazouani** [comment]
@Faari7, @theblixguy thank you guys for your contribution, I updated the Readme by adding some examples, please let me know if it's better now, thanks :) don't hesitate to send a PR if you would like to  add some more details and explanations to the ReadMe

**Comment by Faari7** [comment]
ohh my mistake i was doing that in wrong way. thank you @HamzaGhazouani @theblixguy

**Comment by HamzaGhazouani** [comment]
You are welcome, and it's not your mistake,  the ReadMe also was not very clear about this part :)
