### ISSUE TITLE
Placeholders not showing

### ISSUE THREAD

**Issue by andrerosa189** [HamzaGhazouani/HGPlaceholders#26]
Hey I'm writing the follow code on my tableView

`
import UIKit
import HGPlaceholders

class SentMemesTVC: UITableViewController{

    var placeholderTableView: TableView?
    
    var memes = [Meme]()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.clearsSelectionOnViewWillAppear = false
        
        reloadTable()
      
        NotificationCenter.default.addObserver(self, selector: #selector(reloadTable), name: NSNotification.Name(rawValue: NOTIF_RELOAD_TABLE), object: nil)
        
        
        
        placeholderTableView = tableView as? TableView
        placeholderTableView?.placeholderDelegate = self as PlaceholderDelegate
        
        
        placeholderTableView?.placeholdersProvider = .basic
        placeholderTableView?.showErrorPlaceholder()
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == TO_MEME_EDITOR{
            if let memeEditor = segue.destination as? MemeMainVC{
                if let meme = sender as? Meme{
                    memeEditor.meme = meme
                }
            }
        }
    }
    
    override func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }

    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return memes.count
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if let cell = tableView.dequeueReusableCell(withIdentifier: "MemeTableCell", for: indexPath) as? MemeTableCell{
            let memeCell = memes[indexPath.row]
            cell.configureCell(meme: memeCell)
            return cell
        }
        return UITableViewCell()
    }
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let meme: Meme = memes[indexPath.row]
        performSegue(withIdentifier: TO_MEME_EDITOR, sender: meme)
    }

    override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 114
    }
    
    @objc func reloadTable(){
        let appDelegate = UIApplication.shared.delegate as! AppDelegate
        memes = appDelegate.memes
        self.tableView.reloadData()
    }
    
    @IBAction func toMemeEditor(_ sender: Any){
        performSegue(withIdentifier: TO_MEME_EDITOR, sender: nil)
    }
    
}

extension SentMemesTVC: PlaceholderDelegate {
    
    func view(_ view: Any, actionButtonTappedFor placeholder: Placeholder) {
        print(placeholder.key.value)
        placeholderTableView?.showDefault()
    }
    
}

`

but nothing is happening

**Comment by HamzaGhazouani** [comment]
Hi @andrerosa189, you instantiate the table view via storyboard or by code ?

**Comment by andrerosa189** [comment]
Sorry, but how do I do that?

**Comment by andrerosa189** [comment]
Thanks, I got it

**Comment by HamzaGhazouani** [comment]
Ok :)

**Comment by kimgysen** [comment]
So does this work with Storyboard? I followed the example demo, but the placeholder doesn't show up.
