### ISSUE TITLE
Unable to add custom placeholder

### ISSUE THREAD

**Issue by Faari7** [HamzaGhazouani/HGPlaceholders#28]
1- I created a utility class and assign it to the table view where I needed to use table view placeholder.
2- created a variable in VC "var placeholderTableView: TableView?"
3- In setup GUI
self.placeholderTableView?.placeholdersProvider = .default
self.placeholderTableView?.placeholdersProvider.add(placeholders: TableViewPlaceholder.createPlaceholder1())
4- it show default placeholder not custom placeholder which i setting

**Comment by HamzaGhazouani** [comment]
Hi @Faari7, I update the ReadMe by adding an example of how we can create a new theme, and how to modify an existing theme by adding a new placeholder, let me know if it's clearer now ?, thanks :)
