### ISSUE TITLE
iOS 8.0 Support ?

### ISSUE THREAD

**Issue by aloveric** [HamzaGhazouani/HGPlaceholders#4]

**Comment by aloveric** [comment]
Any plan to support iOS 8?

**Comment by HamzaGhazouani** [comment]
Hi @aloveric, I used UIStackView that's why I supported iOS 9 and later I will add the support of iOS 8 soon

**Comment by aloveric** [comment]
@HamzaGhazouani  Really thanks for support iOS 8.

**Comment by yunzixun** [comment]
when will iOS 8 available?  thanks.

**Comment by HamzaGhazouani** [comment]
Hi @yunzixun, the next release will be available in two weeks

**Comment by HamzaGhazouani** [comment]
Available in [HGPlaceholders 0.3.0](https://github.com/HamzaGhazouani/HGPlaceholders/releases/tag/0.3.0)
