### ISSUE TITLE
Xcode 10.1 and Swift 4.2

### ISSUE THREAD

**Issue by clay-mindoula** [HamzaGhazouani/HGPlaceholders#53]
I have build test projects with the latest pod and by creating a HGPlaceholders.framework. Everything compiles fine but `placeholderTableView = tableView as? TableView` always returns nil?

Using your example project and thing are running as expected.

Any ideas on what I might doing wrong? The following is what I think is the bare minimum tableVC code:

``` import UIKit
import HGPlaceholders

class ViewController: UITableViewController, PlaceholderDelegate {

    var placeholderTableView: TableView?

    override func viewDidLoad() {
        super.viewDidLoad()
        title = "TEST"
        placeholderTableView = tableView as? TableView
        placeholderTableView?.placeholderDelegate = self
        placeholderTableView?.placeholdersProvider = .summer
    }

    func view(_ view: Any, actionButtonTappedFor placeholder: Placeholder) {
        print(placeholder.key.value)
        placeholderTableView?.showDefault()
    }

    override func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }

    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 0
    }
}
```
thx

**Comment by HamzaGhazouani** [comment]
Hi @clay-mindoula, are you using IB ? if yes you should inherit from TableView class: 

<img width="260" alt="capture d ecran 2018-12-03 a 12 17 22" src="https://user-images.githubusercontent.com/2019146/49370769-83980a80-f6f5-11e8-914a-29d86535e1ef.png">

**Comment by clay-mindoula** [comment]
Thanks for getting back so promptly. I am, in that I'm just just a default xcode project which means the above needs to point at the ViewController (UITableView) class I have in my example above. Just tried to include source code and remove any pod dependencies but same issue after fixing things up and running the project. Everything looks good but  tableView as? TableView returns nil. I pawed over your example project which works for "the thing" that might kick things into life but again without luck. Damn shame, really liked your implementation! Again many thanks.  Cheers
