### ISSUE TITLE
Update podspec version

### ISSUE THREAD

**Issue by mmdock** [HamzaGhazouani/HGPlaceholders#56]
Installed via Cocoapods:

pod 'HGPlaceholders'

for swift 4.2: this causes compile errors.  

I see that these have been fixed in the repo, but not for Cocoapods.

In order to install a version compatible with Swift 4.2 I have to install as such: 

pod 'HGPlaceholders', :git => 'https://github.com/HamzaGhazouani/HGPlaceholders.git'

Cocoapods looks at the latest commit at the time it gets submitted and uses that commit to install from for that version.  Since you haven't submitted a new version to Cocoapods, even though you have made new commits for 4.2 compatibility, I have to install use the git url.  

Please update when you have the time.

**Comment by KKLater** [comment]
I also encountered this problem.😿

**Comment by HamzaGhazouani** [comment]
The new version 0.4.0 is now available, thanks guys for reporting
