### ISSUE TITLE
library not work with xcode 12 

### ISSUE THREAD

**Issue by AmrSaied** [HamzaGhazouani/HGPlaceholders#68]

**Comment by kamokaizen** [comment]
XCode 12 conflicted frameworks;
 HGPlaceholders
 Material

'CollectionView' has different definitions in different modules; first difference is definition in module 'HGPlaceholders.Swift' found property name 'collectionViewLayout'

**Comment by HamzaGhazouani** [comment]
Hey Guys, I pushed a new version using Xcode 12, please can you let me know if it's working?

**Comment by kamokaizen** [comment]
i did pod update 
Installing HGPlaceholders 0.5.0 (was 0.4.0)
then build again. seems not compiled error again.

![Screen Shot 2020-10-12 at 1 11 08 PM](https://user-images.githubusercontent.com/3720242/95734649-6ab2f580-0c8c-11eb-9aee-488b440bb5d1.png)

**Comment by HamzaGhazouani** [comment]
Thanks @kamokaizen for checking, do you have this with the Example project?

**Comment by kamokaizen** [comment]
No this screenshot from my project. I have been using a long time this framework in my project.

**Comment by kamokaizen** [comment]
Example project is working with xcode 12. Now tested. But other problem continues.
![Screen Shot 2020-10-12 at 1 22 23 PM](https://user-images.githubusercontent.com/3720242/95735795-fd07c900-0c8d-11eb-8e0d-4b3a340c6ad6.png)

**Comment by HamzaGhazouani** [comment]
I think your issue is related to this one #63 you should add the context: HGPlaceholder.CollectionView instead of CollectionView

**Comment by kamokaizen** [comment]
fixed with like that..
class HGCollectionView: HGPlaceholders.CollectionView {

Thanks @HamzaGhazouani appreciate

**Comment by HamzaGhazouani** [comment]
Great! you are welcome :)
