### ISSUE TITLE
Archiving project fails when using HGPlaceholders as a Pod

### ISSUE THREAD

**Issue by sasojadrovski** [HamzaGhazouani/HGPlaceholders#7]
Hey @HamzaGhazouani,

I have discovered that if you try to archive the project for distribution (AdHoc), and at the same time you have added and are using this library as a Pod, the archiving fails with an error:

> Symbol(s) not found for architecture arm64

I have also verified that this is not a case when the library is added to the project manually.

Please take a look and if you need some additional info, please let me know.

Cheers,
Sasho

**Comment by HamzaGhazouani** [comment]
Hey @sasojadrovski, I tried with two several projects, it's working fine for me...
I use the 1.2.1 cocoapods version, could you please try to update cocoapods `sudo gem install cocoapods` or `pod deintegrate` & `pod update`

Thanks

**Comment by sasojadrovski** [comment]
Hey @HamzaGhazouani, I am running the same version of CocoaPods (v.1.2.1) and I run pod update before archiving, but it failed. I will try it again in the following days and let you know the outcome.

Cheers!

**Comment by HamzaGhazouani** [comment]
Perfect, thanks for your reactivity

**Comment by sasojadrovski** [comment]
No problem, you are welcome 😊

**Comment by sasojadrovski** [comment]
Hey @HamzaGhazouani,

I have just verified, and this issue has been resolved and may now be closed. Issue #15 was also related to this. 

Thank you!
