### ISSUE TITLE
How can I use this?

### ISSUE THREAD

**Issue by MourinhoLove** [HamzaGhazouani/HGPlaceholders#70]
I want to use this for my project.
when I import HGPlaceholders.then set
`    var placeholderTableView: TableView? 
`
`      placeholderTableView = self.tableView as? TableView
`
But The placeholderTableView is nil.
How can I fix this?
Thank you.

**Comment by happiehappie** [comment]
Maybe elaborate on how you created/initialise your tableview? cause it doesn't seem like you're using storyboard?

**Comment by MourinhoLove** [comment]
> 也许详细介绍如何创建/初始化表格视图？原因似乎不是您正在使用情节提要吗？

hhhh.I know how to use this. Thank you.
