### ISSUE TITLE
UITableView header/footer views are not preserved if set programmatically 

### ISSUE THREAD

**Issue by sasojadrovski** [HamzaGhazouani/HGPlaceholders#8]
Hey @HamzaGhazouani,

I have also discovered that if you have let's say a footer added to the `UITableView` (one common example is adding a blank `UIView` inside `viewDidLoad` (e.g. `tableView.tableFooterView = UIView()` to the table view's footer view in order to remove the separators if there are only 1 or 2 rows in the table view) which has been added programmatically in `viewDidLoad` for example, for some reason, the footer view is removed and set to nil.

This is not the case if you have added it via Storyboard.

Could you please take a look?

Cheers,
Sasho

**Comment by HamzaGhazouani** [comment]
Hey @sasojadrovski, could you please confirm that is working fine now? thanks a lot

**Comment by sasojadrovski** [comment]
Hey @HamzaGhazouani,

Just checked it, looks good! Good job and thank you once again!

Cheers!

**Comment by HamzaGhazouani** [comment]
You are welcome :)
